import WebNotifications from "@/app/components/WebNotifications";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/app/components/Provider";
import { auth } from "@/lib/utils/authOptions";
import NavBar from "@/app/components/NavBar";
import { classNames } from "@/lib/utils/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white ">
      <body
        className={classNames(
          inter.className,
          "h-full text-gray-800 dark:text-gray-200 dark:bg-base-100"
        )}
      >
        <Provider session={await auth()}>
          <NavBar>
            <WebNotifications />
            {children}
          </NavBar>
        </Provider>
      </body>
    </html>
  );
}
