import WebNotifications from "@/app/components/WebNotifications";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Provider from "@/app/components/Provider";
2;
import NavBar from "@/app/components/NavBar";
import { classNames } from "@/lib/utils/app";
import { getServerSession } from "next-auth";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="h-full bg-white ">
      <body
        className={classNames(
          inter.className,
          "h-full text-gray-800 dark:text-gray-200 dark:bg-base-100"
        )}
      >
        <Provider session={session}>
          <NavBar>
            {/* <WebNotifications /> */}
            {children}
          </NavBar>
        </Provider>
      </body>
    </html>
  );
}
