import WebNotifications from "@/app/components/WebNotifications";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/app/components/Provider";
import { auth } from "@/lib/utils/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={await auth()}>
          <WebNotifications />
          {children}
        </Provider>
      </body>
    </html>
  );
}
